package com.xiaosong.model;

import com.xiaosong.model.base.BaseVKqRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VKqRecord extends BaseVKqRecord<VKqRecord> {
	public static final VKqRecord dao = new VKqRecord().dao();
}
