package com.xiaosong.model;

import com.xiaosong.model.base.BaseVProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VProduct extends BaseVProduct<VProduct> {
	public static final VProduct dao = new VProduct().dao();
}
