package com.xiaosong.model;

import com.xiaosong.model.base.BaseVUserConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VUserConfig extends BaseVUserConfig<VUserConfig> {
	public static final VUserConfig dao = new VUserConfig().dao();
}
