package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppMenu<M extends BaseVAppMenu<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setFunctionName(java.lang.String functionName) {
		set("function_name", functionName);
		return (M)this;
	}
	
	public java.lang.String getFunctionName() {
		return getStr("function_name");
	}

	public M setMenuCode(java.lang.String menuCode) {
		set("menu_code", menuCode);
		return (M)this;
	}
	
	public java.lang.String getMenuCode() {
		return getStr("menu_code");
	}

	public M setMenuName(java.lang.String menuName) {
		set("menu_name", menuName);
		return (M)this;
	}
	
	public java.lang.String getMenuName() {
		return getStr("menu_name");
	}

	public M setMenuUrl(java.lang.String menuUrl) {
		set("menu_url", menuUrl);
		return (M)this;
	}
	
	public java.lang.String getMenuUrl() {
		return getStr("menu_url");
	}

	public M setSid(java.lang.Long sid) {
		set("sid", sid);
		return (M)this;
	}
	
	public java.lang.Long getSid() {
		return getLong("sid");
	}

	public M setIstop(java.lang.String istop) {
		set("istop", istop);
		return (M)this;
	}
	
	public java.lang.String getIstop() {
		return getStr("istop");
	}

	public M setMenuIcon(java.lang.String menuIcon) {
		set("menu_icon", menuIcon);
		return (M)this;
	}
	
	public java.lang.String getMenuIcon() {
		return getStr("menu_icon");
	}

	public M setRelationNo(java.lang.String relationNo) {
		set("relation_no", relationNo);
		return (M)this;
	}
	
	public java.lang.String getRelationNo() {
		return getStr("relation_no");
	}

	public M setSstatus(java.lang.String sstatus) {
		set("sstatus", sstatus);
		return (M)this;
	}
	
	public java.lang.String getSstatus() {
		return getStr("sstatus");
	}

	public M setExt1(java.lang.String ext1) {
		set("ext1", ext1);
		return (M)this;
	}
	
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	public M setExt2(java.lang.String ext2) {
		set("ext2", ext2);
		return (M)this;
	}
	
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	public M setExt3(java.lang.String ext3) {
		set("ext3", ext3);
		return (M)this;
	}
	
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
