package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppCheckindate<M extends BaseVAppCheckindate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setGroupId(java.lang.Long groupId) {
		set("group_id", groupId);
		return (M)this;
	}
	
	public java.lang.Long getGroupId() {
		return getLong("group_id");
	}

	public M setWorkdays(java.lang.String workdays) {
		set("workdays", workdays);
		return (M)this;
	}
	
	public java.lang.String getWorkdays() {
		return getStr("workdays");
	}

	public M setFlexTime(java.lang.Integer flexTime) {
		set("flex_time", flexTime);
		return (M)this;
	}
	
	public java.lang.Integer getFlexTime() {
		return getInt("flex_time");
	}

	public M setNoneedOffwork(java.lang.String noneedOffwork) {
		set("noneed_offwork", noneedOffwork);
		return (M)this;
	}
	
	public java.lang.String getNoneedOffwork() {
		return getStr("noneed_offwork");
	}

	public M setLimitAheadtime(java.lang.Integer limitAheadtime) {
		set("limit_aheadtime", limitAheadtime);
		return (M)this;
	}
	
	public java.lang.Integer getLimitAheadtime() {
		return getInt("limit_aheadtime");
	}

	public M setExp1(java.lang.String exp1) {
		set("exp1", exp1);
		return (M)this;
	}
	
	public java.lang.String getExp1() {
		return getStr("exp1");
	}

	public M setExp2(java.lang.String exp2) {
		set("exp2", exp2);
		return (M)this;
	}
	
	public java.lang.String getExp2() {
		return getStr("exp2");
	}

}
