package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVBusiness<M extends BaseVBusiness<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setBusinessName(java.lang.String businessName) {
		set("business_name", businessName);
		return (M)this;
	}
	
	public java.lang.String getBusinessName() {
		return getStr("business_name");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setTrueName(java.lang.String trueName) {
		set("true_name", trueName);
		return (M)this;
	}
	
	public java.lang.String getTrueName() {
		return getStr("true_name");
	}

	public M setCreatetime(byte[] createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public byte[] getCreatetime() {
		return get("createtime");
	}

	public M setExtra1(java.lang.String extra1) {
		set("extra1", extra1);
		return (M)this;
	}
	
	public java.lang.String getExtra1() {
		return getStr("extra1");
	}

	public M setExtra2(java.lang.String extra2) {
		set("extra2", extra2);
		return (M)this;
	}
	
	public java.lang.String getExtra2() {
		return getStr("extra2");
	}

	public M setExtra3(java.lang.String extra3) {
		set("extra3", extra3);
		return (M)this;
	}
	
	public java.lang.String getExtra3() {
		return getStr("extra3");
	}

}
