package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVKqRecord<M extends BaseVKqRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public M setGroupId(java.lang.Long groupId) {
		set("group_id", groupId);
		return (M)this;
	}
	
	public java.lang.Long getGroupId() {
		return getLong("group_id");
	}

	public M setGroupName(java.lang.String groupName) {
		set("group_name", groupName);
		return (M)this;
	}
	
	public java.lang.String getGroupName() {
		return getStr("group_name");
	}

	public M setCheckinType(java.lang.String checkinType) {
		set("checkin_type", checkinType);
		return (M)this;
	}
	
	public java.lang.String getCheckinType() {
		return getStr("checkin_type");
	}

	public M setExceptionType(java.lang.String exceptionType) {
		set("exception_type", exceptionType);
		return (M)this;
	}
	
	public java.lang.String getExceptionType() {
		return getStr("exception_type");
	}

	public M setCheckinTime(java.lang.String checkinTime) {
		set("checkin_time", checkinTime);
		return (M)this;
	}
	
	public java.lang.String getCheckinTime() {
		return getStr("checkin_time");
	}

	public M setLocationTitle(java.lang.String locationTitle) {
		set("location_title", locationTitle);
		return (M)this;
	}
	
	public java.lang.String getLocationTitle() {
		return getStr("location_title");
	}

	public M setLocationDetail(java.lang.String locationDetail) {
		set("location_detail", locationDetail);
		return (M)this;
	}
	
	public java.lang.String getLocationDetail() {
		return getStr("location_detail");
	}

	public M setWifiName(java.lang.String wifiName) {
		set("wifi_name", wifiName);
		return (M)this;
	}
	
	public java.lang.String getWifiName() {
		return getStr("wifi_name");
	}

	public M setWifiMac(java.lang.String wifiMac) {
		set("wifi_mac", wifiMac);
		return (M)this;
	}
	
	public java.lang.String getWifiMac() {
		return getStr("wifi_mac");
	}

	public M setCheckinDivice(java.lang.String checkinDivice) {
		set("checkin_divice", checkinDivice);
		return (M)this;
	}
	
	public java.lang.String getCheckinDivice() {
		return getStr("checkin_divice");
	}

	public M setNotes(java.lang.String notes) {
		set("notes", notes);
		return (M)this;
	}
	
	public java.lang.String getNotes() {
		return getStr("notes");
	}

	public M setMediaids(java.lang.String mediaids) {
		set("mediaids", mediaids);
		return (M)this;
	}
	
	public java.lang.String getMediaids() {
		return getStr("mediaids");
	}

	public M setLat(java.lang.Long lat) {
		set("lat", lat);
		return (M)this;
	}
	
	public java.lang.Long getLat() {
		return getLong("lat");
	}

	public M setLng(java.lang.Long lng) {
		set("lng", lng);
		return (M)this;
	}
	
	public java.lang.Long getLng() {
		return getLong("lng");
	}

	public M setCreatTime(java.util.Date creatTime) {
		set("creat_time", creatTime);
		return (M)this;
	}
	
	public java.util.Date getCreatTime() {
		return get("creat_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setExp1(java.lang.String exp1) {
		set("exp1", exp1);
		return (M)this;
	}
	
	public java.lang.String getExp1() {
		return getStr("exp1");
	}

	public M setExp2(java.lang.String exp2) {
		set("exp2", exp2);
		return (M)this;
	}
	
	public java.lang.String getExp2() {
		return getStr("exp2");
	}

	public M setExp3(java.lang.String exp3) {
		set("exp3", exp3);
		return (M)this;
	}
	
	public java.lang.String getExp3() {
		return getStr("exp3");
	}

}
